baseURL = '/'
languageCode = 'en-us'
title = 'Janette Rounds'
theme = "m10c"
paginate = 10
relativeURLs = true
homepage = 'janetterounds.com'

[params]
  author = "Janette Rounds"
  description = "Software Engineer, Nature Fangirl, General Nerd"
  avatar = "./uploads/BatAvatar.png"
  menu_item_separator = "/"
  favicon = "./uploads/favicon.ico"

[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/pherateriw"
[[params.social]]
  icon = "linkedin"
  name = "My LinkedIn"
  url = "https://www.linkedin.com/in/janette-rounds/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 4

[module]
   [[module.imports]]
   path = "github.com/divinerites/plausible-hugo"

[plausible]
  enable = true
  domain = "janetterounds.com"
  outbound_link = true
  file_downloads = true
  debug = true
